
rename INHYR inhyr
rename ANLYR anlyr
rename STMYR stmyr
rename SEDYR sedyr
rename IEMYR iemyr
rename IEMMON iemmon

rename EMPSTATY empstaty
rename	  MJEVER	          mjever
rename	  MJAGE	          	mjage
rename	  MJYFU	          	mjyfu
rename	  MJMFU	          	mjmfu
rename	  MJREC	          	mjrec
rename	  MJYRTOT	          mjyrtot
rename	  MRTOTFG	          mrtotfg
rename	  MJFQFLG	          mjfqflg
rename	  MRBSTWAY	          mrbstway
rename	  MRDAYPYR	          mrdaypyr
rename	  MRDAYPMO	          mrdaypmo
rename	  MRDAYPWK	          mrdaypwk
rename	  MJDAY30A	          mjday30a
rename	  MR30EST	          mr30est
rename	  MORPHINE	          morphine
rename    USDRGTST		usdrgtst
rename IRPINC3 irpinc3
rename	  MRJFLAG	          mrjflag
rename	  MRJYR	          mrjyr
rename	  MRJMON	          mrjmon
rename	  SUMFLAG	          sumflag
rename	  SUMYR	          sumyr
rename	  SUMMON	          summon
rename	  SUMAGE	          sumage
rename	  SUMYFU	          sumyfu
rename	  MJOFLAG	          mjoflag
rename	  MJOYR2	          mjoyr2
rename	  MJOMON2	          mjomon2
rename	  MORPHIN2	          morphin2
rename	  MJAFU	          mjafu
rename	  MRJYDAYS	          mrjydays
rename	  MRJMDAYS	          mrjmdays
rename	  MJLAST3	          mjlast3
rename	  MJRECDK	          mjrecdk
rename	  MJRECRE	          mjrecre
rename	  TOTMJ	          totmj
rename	  MJFRAME3	          mjframe3
rename	  MJYRAVE	          mjyrave
rename	  MJMONAVE	          mjmonave
rename	  MJWKAVE	          mjwkave
rename	  RSKMJOCC	          rskmjocc
rename	  RSKMJREG	          rskmjreg
rename	  RSKDIFMJ	          rskdifmj
rename	  GRSKMOCC	          grskmocc
rename	  GRSKMREG	          grskmreg
rename	  RDIFMJ	          rdifmj
rename	  RSNOMRJ	          rsnomrj
rename	  BLNTNOMJ	          blntnomj
rename	  MRJLOTTM	          mrjlottm
rename	  MRJGTOVR	          mrjgtovr
rename	  MRJLIMIT	          mrjlimit
rename	  MRJKPLMT	          mrjkplmt
rename	  MRJNDMOR	          mrjndmor
rename	  MRJLSEFX	          mrjlsefx
rename	  MRJCUTDN	          mrjcutdn
rename	  MRJCUTEV	          mrjcutev
rename	  MRJEMOPB	          mrjemopb
rename	  MRJEMCTD	          mrjemctd
rename	  MRJPHLPB	          mrjphlpb
rename	  MRJPHCTD	          mrjphctd
rename	  MRJLSACT	          mrjlsact
rename	  MRJSERPB	          mrjserpb
rename	  MRJPDANG	          mrjpdang
rename	  MRJLAWTR	          mrjlawtr
rename	  MRJFMFPB	          mrjfmfpb
rename	  MRJFMCTD	          mrjfmctd

rename	  DEPNDMRJ	          depndmrj
rename	  DEPNDXMJ	          depndxmj
rename	  ABUSEMRJ	          abusemrj
rename	  ABUSEXMJ	          abusexmj
rename	  ABODMRJ	          abodmrj
rename	  BOOKED	          booked
rename	  NOBOOKY2	          nobooky2
rename	  MMGETMJ	          mmgetmj
rename	  MMBTREC1	          mmbtrec1
rename	  MMBTPYR	          mmbtpyr
rename	  MMBTREC2	          mmbtrec2
rename	  MMBT30DY	          mmbt30dy
rename	  MMJNTLOO	          mmjntloo
rename	  MMJNTNUM	          mmjntnum
rename	  MMJNPCTB	          mmjnpctb
rename	  MMJNPCAT	          mmjnpcat
rename	  MMLSUNIT	          mmlsunit
rename	  MMLSGMS	          mmlsgms
rename	  MMLS10GM	          mmls10gm
rename	  MMLSOZS	          mmlsozs
rename	  MMLSLBS	          mmlslbs
rename	  MMLS5LBS	          mmls5lbs
rename	  MMLSPCTB	          mmlspctb
rename	  MMLSPCAT	          mmlspcat
rename	  MMBUYWHO	          mmbuywho
rename	  MMBPLACE	          mmbplace
rename	  MMBPLOS2	          mmbplos2
rename	  MMBATJOB	          mmbatjob
rename	  MMBCLOSE	          mmbclose
rename	  MMBSELL	          mmbsell
rename	  MMBGIVE	          mmbgive
rename	  MMTRADE	          mmtrade
rename	  MMTRD30D	          mmtrd30d
rename	  MMTRDREC	          mmtrdrec
rename	  MMT30FRQ	          mmt30frq
rename	  MMTJNTLS	          mmtjntls
rename	  MMTJNTNM	          mmtjntnm
rename	  MMTJWRCB	          mmtjwrcb
rename	  MMTJWRTH	          mmtjwrth
rename	  MMTLUNIT	          mmtlunit
rename	  MMTLGMS	          mmtlgms
rename	  MMTLOZS	          mmtlozs
rename	  MMTLWRCB	          mmtlwrcb
rename	  MMTLWRTH	          mmtlwrth
rename	  MMTRDWHO	          mmtrdwho
rename	  MMTPLACE	          mmtplace
rename	  MMTPLOS2	          mmtplos2
rename	  MMTCLOSE	          mmtclose
rename	  MMTKEEP	          mmtkeep
rename	  MMTSELL	          mmtsell
rename	  MMTGIVE	          mmtgive
rename	  MMGKEEP	          mmgkeep
rename	  MMGSELL	          mmgsell
rename	  MMGGIVE	          mmggive
rename	  MMFREWHO	          mmfrewho
rename	  MMFPLACE	          mmfplace
rename	  MMFPLOS2	          mmfplos2
rename	  MMFCLOSE	          mmfclose
rename	  MMFKEEP	          mmfkeep
rename	  MMFSELL	          mmfsell
rename	  MMFGIVE	          mmfgive
rename	  MJPGOT	          mjpgot
rename	  MJPBTFRM	          mjpbtfrm
rename	  MJPBTPL2	          mjpbtpl2
rename	  MJPFREGT	          mjpfregt
rename	  MJPFRPL2	          mjpfrpl2
rename	  MRJYRBFR	          mrjyrbfr
rename	  MRJAGLST	          mrjaglst
rename	  MRJYLU	          mrjylu
rename	  MRJMLU	          mrjmlu
rename	  USEALMJ	          usealmj
rename	  MJPRIOR	          mjprior
rename	  MJPRIYR	          mjpriyr
rename	  MJPRNOYR	          mjprnoyr
rename	  NDTMRMJ	          ndtmrmj
rename	  TXLTYMJ	          txltymj
rename	  TXLTMJ2	          txltmj2
rename	  TXSPMRJ	          txspmrj
rename	  FLTNDMRJ	          fltndmrj
rename	  NDEFMRJ	          ndefmrj
rename	  SNFAMJEV	          snfamjev
rename	  YESTSMJ	          yestsmj
rename	  YEPMJEVR	          yepmjevr
rename	  YEPMJMO	          yepmjmo
rename	  YEGMJEVR	          yegmjevr
rename	  YEGMJMO	          yegmjmo
rename	  YEFMJEVR	          yefmjevr
rename	  YEFMJMO	          yefmjmo
rename	  SCHFELT	          schfelt
rename	  STNDSMJ	          stndsmj
rename	  YOSELL2	          yosell2
rename	  FRDMEVR2	          frdmevr2
rename	  FRDMJMON	          frdmjmon
rename	  PRVDRGO2	          prvdrgo2
rename	  GRPCNSL2	          grpcnsl2
rename	  CADRKMRJ	          cadrkmrj
rename IRSEX irsex
rename	  INCOME	          income
rename	  POVERTY2	          poverty2
rename QUESTID questid
rename	  AGE2	          age2
rename	  NOMARR2	          nomarr2
rename	  HEALTH	          health

rename	  CATAGE	          catage
rename	  CATAG2	          catag2
rename	  CATAG3	          catag3
rename	  CATAG6	          catag6
rename	  CATAG7	          catag7
rename	  SEXAGE	          sexage
rename	  NEWRACE2	          newrace2
rename	  SEXRACE	          sexrace
rename	  EDUCCAT2	          educcat2
rename	  EDUCATHP	          educathp
rename	  MOVESPY2	          movespy2
rename	  MOVYRFLG	          movyrflg
rename	  SCHENRL	          schenrl
rename	  EDUCATN2	          educatn2
rename	  SCHDSICK	          schdsick
rename	  SCHDSKIP	          schdskip
rename	  HSGED	          hsged
rename	  LFSCHWH2	          lfschwh2
rename	  COLLENR	          collenr
rename	  COLLENR2	          collenr2
rename	  JBSTATR2	          jbstatr2
rename	  WRKHAVJB	          wrkhavjb
rename	  WRKHRSW2	          wrkhrsw2
rename	  WRKIDST2	          wrkidst2
rename	  WRKOCUP2	          wrkocup2
rename	  WRKBZCA2	          wrkbzca2
rename	  WRKEDYR	          wrkedyr
rename	  WRKSLFEM	          wrkslfem
rename	  WRKJOBS2	          wrkjobs2
rename	  WRKUNEMP	          wrkunemp
rename	  WRKUNWKS	          wrkunwks
rename	  WRKLSTY2	          wrklsty2
rename	  WRKIDSY2	          wrkidsy2
rename	  WRKOCUY2	          wrkocuy2
rename	  WRKBZCY2	          wrkbzcy2
rename	  LOCSIZE	          locsize
rename	  DRGPLCY	          drgplcy
rename	  PLCYCOV	          plcycov
rename	  WKDRGED	          wkdrged
rename	  DRGPRGM	          drgprgm
rename	  USALCTST	          usalctst
rename	  TSTHIRE	          tsthire
rename	  TSTRAND	          tstrand
rename	  FIRSTPOS	          firstpos
rename	  WRKHIRE	          wrkhire
rename	  WORKRAND	          workrand
rename	  PDEN	          pden

rename	  MRJONFL	          mrjonfl
rename	  MRJONYR	          mrjonyr
rename	  MRJONMO	          mrjonmo
rename	  MJCGONFL	          mjcgonfl
rename	  MJCGONYR	          mjcgonyr
rename	  MJCGONMO	          mjcgonmo
rename	  MJALONFL	          mjalonfl
rename	  MJALONYR	          mjalonyr
rename	  MJALONMO	          mjalonmo
rename	  MJIEONFL	          mjieonfl
rename	  MJIEONYR	          mjieonyr
rename	  MJIEONMO	          mjieonmo
rename	  SCHWORK	          schwork
rename	  SCHIMPT	          schimpt
rename	  SCHINTST	          schintst
rename	  SCHTYPE	          schtype
rename	  SCHRELGS	          schrelgs
rename	  SCHLOGRD	          schlogrd
rename	  SCHHIGRD	          schhigrd
rename	  MJPBTPLC	          mjpbtplc
rename	  MJPFREPL	          mjpfrepl
rename	  POVERTY	          poverty
rename	  MRJPRIOR	          mrjprior
rename	  YECGRWMJ	          yecgrwmj
rename	  SNFDMJ	          snfdmj
rename	  WRKINDU2	          wrkindu2
rename	  WRKOCCU2	          wrkoccu2
rename	  WRKINDY2	          wrkindy2
rename	  WRKOCCY2	          wrkoccy2

rename	  WRKHRSWK	          wrkhrswk
rename	  COLLEGE2	          college2

rename	  EDUCNOW2	          educnow2
rename	  WRKEFFRT	          wrkeffrt
rename	  WRKLASY2	          wrklasy2


